### ISSUE TITLE
Example settings in README doesn't match code in feature/dlcs_api_rewrite

### ISSUE THREAD

**Issue by alexwlchan** [dlcs/dlcs-cli#4]
I've checked out `feature/dlcs_api_rewrite` at commit `4422139`.

I copied the example settings file from the README:

```python
DLCS_ENTRY = 'https://api.dlcs' # the route of the API to call (e.g. https://api.dlcs.io)
DLCS_API_KEY = '[redacted]' # username for basic auth
DLCS_SECRET = '[redacted]' # password for basic auth
DLCS_CUSTOMER_ID = 2  # Wellcome
DLCS_SPACE_ID = 7  # Miro test
# DLCS_ORIGIN = 'storage-origin' # bucket used to upload to (optional)
```

but when I run the CLI, I get an error:

```console
$ python3 dlcs-cli.py
Traceback (most recent call last):
  File "dlcs-cli.py", line 6, in <module>
    from commands import (
  File "/Users/alexwlchan/repos/dlcs-cli/commands/__init__.py", line 1, in <module>
    from .customer import CustomerCommands
  File "/Users/alexwlchan/repos/dlcs-cli/commands/customer.py", line 3, in <module>
    from settings import DLCS_CUSTOMER_ID, DLCS_SPACE_ID
ImportError: cannot import name 'DLCS_SPACE_ID' from 'settings' (/Users/alexwlchan/repos/dlcs-cli/settings.py)
```

I can change the settings easily, but it's not clear how it should be fixed – should the README be updated, or the CLI?

**Comment by alexwlchan** [comment]
Also:

* DLCS_ENTRY has become DLCS_API_URL
* DLCS_API_KEY has become DLCS_KEY

**Comment by stephenwf** [comment]
Feels like we should make the configuration resilient if it previously used the settings from the read-me, in the situation where someone upgrades the CLI version.
